# Generated by Django 3.2 on 2021-04-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('balance', models.IntegerField(default=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wallet', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wallet', to='wallet.wallet')),
            ],
        ),
    ]
